### ISSUE TITLE
New release on rubygems?

### ISSUE THREAD

**Issue by mdoyle13** [FormAPI/libreconv#22]
Hi there,

Do you know when / if there will be a new release on rubygems with the latest updates?

**Comment by andres107** [comment]
You can force it, and get new changes from github using in your Gemfile
```bash
gem 'libreconv', github: 'FormAPI/libreconv', branch: 'master'
```
However I was getting an error in production environment with libreoffice 5.3.6.1 30, so I changed for libreoffice version 6.1.5 and it works.

**Comment by ndbroadbent** [comment]
Sorry for the delay, I hope to get access to rubygems and release a new version soon!

**Comment by omairrazam** [comment]
Hi.
using the above mentioned branch I am getting following error.
'closed stream'

Trace give me this

These are few lines of trace

["/Users/umair/.rvm/gems/ruby-2.6.0/bundler/gems/libreconv-b3156e2efa7b/lib/libreconv.rb:121:in `exist?'",
"/Users/umair/.rvm/gems/ruby-2.6.0/bundler/gems/libreconv-b3156e2efa7b/lib/libreconv.rb:121:in `check_source_type'",
"/Users/umair/.rvm/gems/ruby-2.6.0/bundler/gems/libreconv-b3156e2efa7b/lib/libreconv.rb:33:in `initialize'",
"/Users/umair/.rvm/gems/ruby-2.6.0/bundler/gems/libreconv-b3156e2efa7b/lib/libreconv.rb:19:in `new'","/Users/umair/.rvm/gems/ruby-2.6.0/bundler/gems/
